CREATE TABLE menu
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    menu_id   BIGINT,
    name      VARCHAR(255),
    url       VARCHAR(255),
    status    VARCHAR(255),
    parent_id BIGINT,
    CONSTRAINT pk_menu PRIMARY KEY (id)
);

ALTER TABLE menu
    ADD CONSTRAINT FK_MENU_ON_PARENT FOREIGN KEY (parent_id) REFERENCES menu (id);
