CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username    VARCHAR(255)                            NOT NULL,
    password    VARCHAR(255),
    authorities VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

CREATE TABLE menu
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    menu_id   BIGINT,
    name      VARCHAR(255),
    url       VARCHAR(255),
    status    VARCHAR(255),
    parent_id BIGINT,
    CONSTRAINT pk_menu PRIMARY KEY (id)
);

ALTER TABLE menu
    ADD CONSTRAINT FK_MENU_ON_PARENT FOREIGN KEY (parent_id) REFERENCES menu (id);