CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username    VARCHAR(255)                            NOT NULL,
    password    VARCHAR(255),
    email       VARCHAR(255),
/*    authorities VARCHAR(255),*/
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

CREATE TABLE menu
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    menu_id   BIGINT,
    name      VARCHAR(255),
    url       VARCHAR(255),
    status    VARCHAR(255),
    parent_id BIGINT,
    CONSTRAINT pk_menu PRIMARY KEY (id)
);

ALTER TABLE menu
    ADD CONSTRAINT FK_MENU_ON_PARENT FOREIGN KEY (parent_id) REFERENCES menu (id);

CREATE TABLE roles
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);


CREATE TABLE users_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);


ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);