jwt:
  auth:
    converter:
      resource-id: ${spring.application.name}
      principal-attribute: preferred_username
server:
  error:
    whitelabel:
      enabled: false
    include-message: always
    path: /error
  port: 8080
  address: localhost
logging:
  level:
    root: error
    org.springframework.security: DEBUG
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: jdbc:h2:mem:maindb
  security:
    oauth2:
      client:
        registration:
          study:
            provider: spring
            client-id: study
            client-secret: secret
            authorization-grant-type: authorization_code
#            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            scope: openid, study
            client-name: study
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9000

  sql:
    init:
      mode: never


  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: study
  cloud:
    config:
      enabled: false
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: study
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  health:
    defaults:
      enabled: true

eureka:
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 29
